---
- name: Ensure group {{ mq_group }} gid = {{ mq_guid }} exists
  group:
    name: "{{ mq_group }}"
    gid: "{{ mq_guid }}"
    state: present
  become: yes
- name: Add the user {{ mq_user }} uid = {{ mq_uid }}
  user:
    name: "{{ mq_user }}"
    shell: /bin/bash
    group: "{{ mq_group }}"
    uid: "{{ mq_uid }}"
    comment: User MQ Admin
  become: yes
- name: Install apache bc
  package:
    name: bc
    state: present
  become: yes
- name: Modifying Kernel Settings for MQ
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: yes
  with_items: "{{ sysctl_settings }}"
  become: yes
  when: ansible_facts['virtualization_type'] != "docker"
- name: Set user {{ mq_user }} limits
  template:
    src: mqm-limits.j2
    dest: "/etc/security/limits.d/{{ mq_user }}-limits.conf"
  become: yes