- name: untar install archive
  unarchive: 
  
   src:  "{{mq_install_dir}}{{mq_installers['mq_'+ansible_facts.os_family+'_package']}}" 
   dest: "{{mq_install_dir}}" 
   copy: no
   creates: "{{mq_install_dir}}{{mq_uncompress_dir}}"
  become: yes

- name: Accept License
  shell: chdir="{{mq_install_dir}}{{mq_uncompress_dir}}" ./mqlicense.sh -accept -text_only
  become: yes

- name: install with linux distro command
  shell: chdir="{{mq_install_dir}}{{mq_uncompress_dir}}" {{mq_installers['mq_'+ansible_facts.os_family+'_cmd']}} 
  become: yes
  register: result
  failed_when: result.rc not in [0,34]

- name: setmqinst path
  shell: chdir=/opt/mqm/bin ./setmqinst -i -p /opt/mqm
  become: yes