---
- name: Accept License
  shell: chdir="{{ mq_install_dir }}{{ mq_uncompress_dir }}" ./mqlicense.sh -accept -text_only
  become: yes
- name: install with linux distro command
  shell: chdir="{{ mq_install_dir }}{{ mq_uncompress_dir }}" {{ mq_installers['mq_'+ansible_facts.os_family+'_cmd'] }}
  become: yes
  register: result
  failed_when: result.rc not in [0,34]
- name: setmqinst path
  shell: chdir=/opt/mqm/bin ./setmqinst -i -p /opt/mqm
  become: yes
- name: Create Queue Manager
  command: crtmqm -c "MQ For dev" -lc -lf 4096 -lp 10 -ls 15  -p 1414 -q -u "{{ mq_qm_name }}.DLQ" "{{ mq_qm_name }}"
  become: true
  become_user: mqm
  register: result
  failed_when: result.rc not in [0,8]
- name: install service for QM
  template:
    src: mq-service.j2
    dest: "/lib/systemd/system/{{ mq_qm_name }}.service"
  become: yes
- name: enable service "{{ mq_qm_name }}"
  systemd:
    name: "{{ mq_qm_name }}"
    enabled: yes
    masked: no
  become: yes
- name: install service for MQ Console
  template:
    src: mqweb-service.j2
    dest: "/lib/systemd/system/mq-webconsole.service"
  become: yes
- name: enable service MQ web console
  systemd:
    name: mq-webconsole
    enabled: yes
    masked: no
  become: yes