---

- name: setmqinst path
  shell: chdir=/opt/mqm/bin ./setmqinst -i -p /opt/mqm

- name: Create Queue Manager
  command: crtmqm -c "MQ For dev" -lc -lf 4096 -lp 10 -ls 15  -p 1414 -q -u "{{mq_install.qm_name}}.DLQ" "{{mq_install.qm_name}}"
  become: true
  become_user: mqm
  become_method: su
  register: result
  failed_when: result.rc not in [0,8]  

- name: Start Queue Manager
  command: strmqm "{{mq_install.qm_name}}"
  become: true
  become_user: mqm
  become_method: su
  register: result
  failed_when: result.rc not in [0,5] 

