- name: Enable Web Server connections
  shell: setmqweb properties -k httpHost -v "*"
  become: true
  become_user: "{{ mq_user }}"
- name: start web server
  shell: su - mqm -c strmqweb 
  become: true
  register: result
  tags:
   - runweb
  failed_when: result.rc not in [0,1]