---

- name: Ensure group "mqclient" exists
  group:
    name: mqclient
    state: present

- name: Add the user Admin
  user:
    name: admin
    password: "{{mq_install.mq_admin_password}}"
    shell: /bin/bash
    group: "{{mq_system.group}}"
    comment: User Admin

- name: Add the user app
  user:
    name: app
    shell: /bin/bash
    group: mqclient
    comment: User For MQ Apps

- name: Set Webmqm config
  template:
    src: basic_registry.j2
    dest: "/var/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml"

- name: Enable Web Server connections
  command: setmqweb properties -k httpHost -v "*"
  become: true
  become_user: mqm
  become_method: su

- name: start web server
  command: strmqweb
  become: true
  become_user: mqm
  become_method: su

